
weird_nouns = [
	"agastopia",
	"kakorrhaphiophobia",
	"lamprophony",
	"zoanthropy",
]
weird_verbs = [
	"bibble (not Bible)",
	"impignorate",
	"xertz",
]
weird_adjectives = [
	"moribund",
	"baleful",
	"prurient",
	"ruminant",
	"vapid",
	"bereft",
]

first_ofenses = [
	"You don't make much sense to me.",
	"Reading your comment is the same as urinating water.",
	"I would rather do something else than participate in this discussion, "\
		"but I couldn't stand reading your comment and not reacting.",
	"I intensively disagree with you.",
	"You don't seem to be using your brains properly.",
	"This conversation is getting childish (intellectually I mean), let me help.",
	"Please don't ruin the discussion with your thoughtless rants.",
	"I'm here to discuss like an adult. Can you please cooperate?",
	"Too stupid; didn't read.",
]
second_sentence_starters = [
	"Please consider carefully that",
	"Therefore,",
	"Nevertheless,",
	"So, as you can probably guess,",
	"Because of that, and nothing else,",
	"It should be a rather non-ignoring fact that",
	"Listen,",
	"I think, but I'm not sure, that",
	"You know, basic stuff. Like",
	"I don't care, but it seems clear to me that",
]
generic_singular_subjects = [
	"idiocracy",
	"irrationality",
	"condescension",
	"stupidity",
	"disarrogance",
	"disdain",
	"exemption",
	"physicality",
	"penalty",
	"illusion",
	"trigger",
	"loophole",
	"transition",
	"leverage ratio",
	"anger",
	"disgust",
]
generic_adjectives = [
	"collective",
	"disinspirational",
	"invisible",
	"destructive",
	"foregone",
	"important",
	"custom",
	"unclear",
	"standard",
	"obligatory",
	"constant",
	"unhuman",
	"conditional",
]
generic_subject_descriptors = [
	"that we dearly consider (or not, depending on the situation) mature enough",
	"which is the purpose of this whole discussion (isn't it?)",
	"or something like that which is never the same",
	"(or perhaps a better description is common sense already)",
	"which includes (but not necessarily) itself as solution",
	"that IRRITATES me",
	"that I see basically every single day",
]
generic_singular_verbs = [
	"promotes",
	"is including",
	"may or may not (dispensive of YOUR OPINION) be like",
	"disregards",
	"is like",
	"is as similar as (but not unexact)",
	"should ignore",
	"COULD derive from",
	"is not better than the absence of",
	"blows up",
	"deconstructs",
	"disallows",
]
generic_singular_objects = [
	"the basic assumption of life that we possess as society (or societies)",
	"a better understanding of what I do not see in this discussion",
	"the BEST way of not including it at all, actually",
	"a nonsense bag of excuses, like the ones these people say",
	"a better discussion than this one here, of course",
	"the infidelity of fake \"nations\" if you know what I mean",
	"a greedy spirit (not like mine)",
	"the basic FACT that you've been insisting in ignoring all the time",
	"the accusation that I have to face",
	"the never ending inclusion of stupid comments into this discussion",
	"the \"spiritual\" revenue generated by the so-called \"spirit debts\"",
	"the work that produces ideas of reinvention, revolution, and intention",
]
confusing_sentence_formats = [
	"%(subject)s which is, to me, rather %(adjective)s.",
	"This %(subject)s is somewhat %(adjective)s.",
	"Very %(adjective)s %(subject)s."
]
generic_comparisons = [
	"It is like",
	"Something like",
	"Take, for instance,",
	"What do I mean?",
	"We can compare this to",
	"Which leads us to consider",
]
after_confusion_sentences = [
	"This is not an easy subject to follow, I know. " \
		"But not everyone is talented, not everyone is GIFTED.",
	"If then one considers these things with a bit more caution, he(she) " \
		"will come to reasonable conclusions. This is not nonsense.",
	"The intensity of all these things is many times confusing to people. " \
		"I don't really think it's confusing. But hey, I don't care, you go " \
		"figure it out. It's your problem.",
	"I tell this to close friends of mine once in a while. Some understand it " \
		"immediately, others don't. I guess it's just one of those things in " \
		"life that aren't common sense.",
	"I can't make it sound simpler than this. These words are really precisely " \
		"crafted.",
	"Now I hope you are following this argument, I would hate to have to explain " \
		"it in deeper details (no time for that, lately).",
	"It took me some years to get this kind of mindset, I would be surprised " \
		"if you understood it immediately. I don't think you will.",
	"I learned this with one professor in college. People thought he was crazy " \
		"but I spent some time talking with him in the corridor and figured out " \
		"the guy was a genious.",
	"All things considered, if none of this made sense to you, well, sorry dude, "\
		"not everyone is able to. I won't chew it down for you."
]
first_questions = [
	"Do you really think you're smart enough?",
	"When did you start thinking like that?",
	"WTF?",
	"Are you out of your little mind?",
	"Are you what, crazy?",
]
middle_questions = [
	"Are you following? You should be.",
	"Can't you see?",
	"Right? Isn't it?",
	"Agree?",
]
last_questions = [
	"Can you answer me?",
	"What do you think you would rather disagree with?",
	"So what do YOU care about?",
	"Who chooses?",
	"Who would say otherwise? YOU?",
	"Else, why did you even join this discussion in the first place?",
]

